### ISSUE TITLE
CDS in HLA-E

### ISSUE THREAD

**Issue by aklussmeier** [ANHIG/IMGTHLA#229] opened 2020-08-26 09:19 UTC
While following an issue with TypeLoader we stumbled upon a release-issue we don’t really understand. May be you can help with that.
In contrast to the other HLAs, HLA-E has the preliminary stop-codon in exon 7 (f.e. HLA-E 01:01:01:01: it ends on codons CAC AGC TTG **TAA**). This is the sequence your website CDS alignments show and it also fits to the translated protein sequence (…HSL). However, if I look into the current release (example: HLA-E*01:01:01:01), the CDS-annotation additionally includes the two last bases of exon 7 and the five bases belonging to exon 8 (join(301..364,495..764,1009..1284,1906..2181,2306..2422, 3173..3205,3310..3352,**3518..3522**). In our case, this collides with a TypeLoader background check that CDS sequences need to be multiples of 3 to not be null alleles. We could of course fix this issue on our end, but I’m still wondering about the discrepancy between the release and the alignment on your website. Thanks!

**Comment by bmschoene** [comment] 2020-08-27 12:57
Note: The problem is in the hla.dat file, which we still use as primary source for allele sequences and annotations, and affects all HLA-E sequences.

**Comment by dominicbarkerAN** [comment] 2020-09-04 14:34
Thank you for bringing this issue to  our attention. The discrepancy occurs due to the marking up of non-coding exons. These exons are included in the mRNA however as there is an early termination stop codon in a prior exon they do not appear in the CDS. In our online alignments we include these non-coding exons in the genomic alignments but do not include them in the CDS alignments. We are now reviewing how we handle these exons in our alignments and files we produce - such as the hla.dat file.

**Comment by bmschoene** [comment] 2020-10-27 09:09
This issue appears to be unfixed in the new release 3.42?

**Comment by bmschoene** [comment] 2020-10-27 13:07
@jrob119 Please reopen, or have you decided to keep the hla.dat this way?

**Comment by jrob119** [comment] 2020-10-27 16:25
We are still reviewing how we can display this information, as we need to encode both the CDS and the exons coordinates, and apply any changes to a number of files. This could also potentially cover more than HLA-E, and may impact on how other features like splice variants or variably expressed exons are encoded.

**Comment by bmschoene** [comment] 2020-10-28 07:53
I see. But why did you close the issue if you still haven't decided on a way to adress it?

**Comment by jrob119** [comment] 2020-10-28 14:03
Re-opening as issue remains in files

**Comment by jrob119** [comment] 2021-01-19 09:33
Amendments to HLA-E CDS line have been made in the latest release.

**Closed as completed by jrob119** 2021-01-19 09:33 UTC
